AWSTemplateFormatVersion: "2010-09-09"
Description: "Core stack for my Medium Article"
Resources:
# Network
  Vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
  Igw:
    Type: "AWS::EC2::InternetGateway"
  VpcIgwAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref Igw
  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref Vpc
  Route:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref Igw
  Subnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: True
  SubnetRtAssoc1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Subnet1
      RouteTableId: !Ref RouteTable
  Subnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref Vpc
      CidrBlock: "10.0.2.0/24"
      MapPublicIpOnLaunch: True
  SubnetRtAssoc2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Subnet2
      RouteTableId: !Ref RouteTable
  # ECS
  TaskRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowFargateToAssumeRole"
            Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
  TaskPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "FargateTaskPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ssm:GetParameter"
              - "ssm:DescribeParameters"
            Resource: "*"
      Roles:
        - !Ref TaskRole
  Ecr:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "myrepo"
  Cluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: "mycluster"
  # SSM
  TaskValueParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Type: String
      Name: "AppValue"
      Description: "The value our simple app will show"
      Value: "Default"

Outputs:
  Subnet1:
    Description: "Id of Subnet1"
    Value: !Ref Subnet1
    Export:
      Name: SUBNET1ID
  Subnet2:
    Description: "Id of Subnet2"
    Value: !Ref Subnet2
    Export:
      Name: SUBNET2ID
  Vpc:
    Description: "Id of VPC"
    Value: !Ref Vpc
    Export:
      Name: VPC
  Ecr:
    Description: "Repository name"
    Value: !Ref Ecr
    Export:
      Name: ECR
  Ecs:
    Description: "ECS Cluster"
    Value: !Ref Cluster
    Export:
      Name: ECS
